import type { GisLayer, LegendItem } from "@/lib/schemas";

type LayerSeed = Omit<GisLayer, "source" | "serviceMode" | "supportsFeatureInfo"> & {
  tpvdLayerName?: string;
  serviceMode?: GisLayer["serviceMode"];
  supportsFeatureInfo?: boolean;
};

const tpvdSource = "Live TPVD GeoServer WMS";

const layer = (seed: LayerSeed): GisLayer => ({
  source: seed.tpvdLayerName ? tpvdSource : "Mock TPVD-style GeoJSON",
  serviceMode: seed.serviceMode ?? (seed.tpvdLayerName ? "tpvd-wms" : "mock-vector"),
  supportsFeatureInfo: seed.supportsFeatureInfo ?? seed.id === "final-plot-boundary",
  ...seed
});

export const gisLayers: GisLayer[] = [
  layer({
    id: "tps-boundary",
    name: "tps-boundary",
    displayName: "TPS Boundary",
    category: "Boundary",
    geometryType: "line",
    description: "Town planning scheme boundary from TPVD's core TPS viewer.",
    color: "#2563eb",
    opacity: 0.9,
    enabledByDefault: true,
    legendLabel: "TPS boundary",
    tpvdLayerName: "ctp:tps_boundary",
    supportsFeatureInfo: true,
    minZoom: 8,
    maxZoom: 19
  }),
  layer({
    id: "final-plot-boundary",
    name: "final-plot-boundary",
    displayName: "Final Plot Boundary",
    category: "Plot",
    geometryType: "line",
    description: "Final plot boundary after TP reconstitution; TPVD click popups are sourced from this layer.",
    color: "#059669",
    opacity: 0.95,
    enabledByDefault: true,
    legendLabel: "Final plot boundary",
    tpvdLayerName: "ctp:final_plot_boundary",
    supportsFeatureInfo: true,
    minZoom: 10,
    maxZoom: 19
  }),
  layer({
    id: "original-plot-boundary",
    name: "original-plot-boundary",
    displayName: "Original Plot Boundary",
    category: "Plot",
    geometryType: "line",
    description: "Original plot boundary before TP final plot reconstitution.",
    color: "#7c3aed",
    opacity: 0.76,
    enabledByDefault: true,
    legendLabel: "Original plot boundary",
    tpvdLayerName: "ctp:original_plot_boundary",
    minZoom: 10,
    maxZoom: 19
  }),
  layer({
    id: "survey-line",
    name: "survey-line",
    displayName: "Survey Line",
    category: "Boundary",
    geometryType: "line",
    description: "Survey demarcation linework visible in TPVD primary layers.",
    color: "#64748b",
    opacity: 0.72,
    enabledByDefault: true,
    legendLabel: "Survey line",
    tpvdLayerName: "ctp:survey_line",
    minZoom: 11,
    maxZoom: 19
  }),
  layer({
    id: "survey-number-labels",
    name: "survey-number-labels",
    displayName: "Survey Number",
    category: "Label",
    geometryType: "symbol",
    description: "Survey number label layer from TPVD's primary layer list.",
    color: "#334155",
    opacity: 1,
    enabledByDefault: true,
    legendLabel: "Survey number",
    tpvdLayerName: "ctp:survey_no",
    minZoom: 13,
    maxZoom: 19
  }),
  layer({
    id: "plot-labels",
    name: "plot-labels",
    displayName: "Plot Labels",
    category: "Label",
    geometryType: "symbol",
    description: "Final/original plot labels and search centroids for inspection.",
    color: "#0f172a",
    opacity: 1,
    enabledByDefault: false,
    legendLabel: "Plot label",
    serviceMode: "mock-vector",
    minZoom: 13,
    maxZoom: 19
  }),
  layer({
    id: "hissa-line",
    name: "hissa-line",
    displayName: "Hissa Line",
    category: "Boundary",
    geometryType: "line",
    description: "Sub-survey parcel or hissa demarcation lines.",
    color: "#8b5cf6",
    opacity: 0.85,
    enabledByDefault: false,
    legendLabel: "Hissa / sub-parcel line",
    tpvdLayerName: "ctp:hissa_line",
    minZoom: 12,
    maxZoom: 19
  }),
  layer({
    id: "village-boundary",
    name: "village-boundary",
    displayName: "Village Boundary",
    category: "Boundary",
    geometryType: "line",
    description: "Revenue village boundary context around TP schemes.",
    color: "#0f766e",
    opacity: 0.8,
    enabledByDefault: true,
    legendLabel: "Village boundary",
    tpvdLayerName: "ctp:village_boundary",
    minZoom: 8,
    maxZoom: 19
  }),
  layer({
    id: "water-body",
    name: "water-body",
    displayName: "Water Body",
    category: "Constraint",
    geometryType: "fill",
    description: "Water body layer; TPVD uses water-body and water-bodies naming variants.",
    color: "#0ea5e9",
    opacity: 0.42,
    enabledByDefault: true,
    legendLabel: "Water body",
    tpvdLayerName: "ctp:water_body",
    minZoom: 8,
    maxZoom: 19
  }),
  layer({
    id: "canal",
    name: "canal",
    displayName: "Canal",
    category: "Constraint",
    geometryType: "line",
    description: "Canal layer included in TPVD's legend list.",
    color: "#0284c7",
    opacity: 0.72,
    enabledByDefault: false,
    legendLabel: "Canal",
    tpvdLayerName: "ctp:canal",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "river",
    name: "river",
    displayName: "River",
    category: "Constraint",
    geometryType: "fill",
    description: "River and river influence layer from TPVD legend.",
    color: "#38bdf8",
    opacity: 0.42,
    enabledByDefault: false,
    legendLabel: "River",
    tpvdLayerName: "ctp:river",
    minZoom: 8,
    maxZoom: 19
  }),
  layer({
    id: "gamthal-boundary",
    name: "gamthal-boundary",
    displayName: "Gamthal / Gamtal Boundary",
    category: "Constraint",
    geometryType: "line",
    description: "Gamtal settlement boundary as named by TPVD.",
    color: "#d97706",
    opacity: 0.88,
    enabledByDefault: false,
    legendLabel: "Gamtal boundary",
    tpvdLayerName: "ctp:gamtal_boundary",
    minZoom: 10,
    maxZoom: 19
  }),
  layer({
    id: "road-network",
    name: "road-network",
    displayName: "Road",
    category: "Road",
    geometryType: "line",
    description: "TPVD road network and TP roads.",
    color: "#334155",
    opacity: 0.72,
    enabledByDefault: true,
    legendLabel: "Road",
    tpvdLayerName: "ctp:road",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "road-boundary",
    name: "road-boundary",
    displayName: "Road Boundary",
    category: "Road",
    geometryType: "line",
    description: "Road right-of-way and boundary lines. Mock-vector fallback where TPVD publishes road as a single layer.",
    color: "#111827",
    opacity: 0.82,
    enabledByDefault: false,
    legendLabel: "Road boundary",
    serviceMode: "mock-vector",
    minZoom: 11,
    maxZoom: 19
  }),
  layer({
    id: "building-structure",
    name: "building-structure",
    displayName: "Building Structure",
    category: "Plot",
    geometryType: "fill",
    description: "Existing building footprint/structure layer from the TPVD legend list.",
    color: "#64748b",
    opacity: 0.35,
    enabledByDefault: false,
    legendLabel: "Building structure",
    tpvdLayerName: "ctp:building_structure",
    minZoom: 13,
    maxZoom: 19
  }),
  layer({
    id: "building-structure-line",
    name: "building-structure-line",
    displayName: "Building Structure Line",
    category: "Plot",
    geometryType: "line",
    description: "Building structure linework.",
    color: "#475569",
    opacity: 0.7,
    enabledByDefault: false,
    legendLabel: "Building structure line",
    tpvdLayerName: "ctp:building_structure_line",
    minZoom: 13,
    maxZoom: 19
  }),
  layer({
    id: "compound-wall",
    name: "compound-wall",
    displayName: "Compound Wall",
    category: "Plot",
    geometryType: "line",
    description: "Compound wall linework shown as a site condition.",
    color: "#92400e",
    opacity: 0.75,
    enabledByDefault: false,
    legendLabel: "Compound wall",
    tpvdLayerName: "ctp:compound_wall",
    minZoom: 13,
    maxZoom: 19
  }),
  layer({
    id: "dp-reservation",
    name: "dp-reservation",
    displayName: "DP Reservation Line",
    category: "Constraint",
    geometryType: "line",
    description: "Development plan reservation line impacts.",
    color: "#f59e0b",
    opacity: 0.72,
    enabledByDefault: true,
    legendLabel: "DP reservation line",
    tpvdLayerName: "ctp:dp_reservation_line",
    minZoom: 10,
    maxZoom: 19
  }),
  layer({
    id: "flood-embankment",
    name: "flood-embankment",
    displayName: "Flood Embankment",
    category: "Constraint",
    geometryType: "line",
    description: "Flood embankment constraint layer from TPVD legend.",
    color: "#0891b2",
    opacity: 0.78,
    enabledByDefault: false,
    legendLabel: "Flood embankment",
    tpvdLayerName: "ctp:flood_embankment",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "ongc-pipeline",
    name: "ongc-pipeline",
    displayName: "ONGC Pipeline",
    category: "Utility",
    geometryType: "line",
    description: "ONGC pipeline utility corridor shown in TPVD legends.",
    color: "#be123c",
    opacity: 0.85,
    enabledByDefault: false,
    legendLabel: "ONGC pipeline",
    tpvdLayerName: "ctp:ongc_pipeline",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "ht-line",
    name: "ht-line",
    displayName: "HT Line",
    category: "Utility",
    geometryType: "line",
    description: "High-tension electricity line constraints.",
    color: "#ef4444",
    opacity: 0.9,
    enabledByDefault: true,
    legendLabel: "HT line",
    tpvdLayerName: "ctp:ht_line",
    minZoom: 10,
    maxZoom: 19
  }),
  layer({
    id: "railway-boundary",
    name: "railway-boundary",
    displayName: "Railway Boundary",
    category: "Constraint",
    geometryType: "line",
    description: "Railway boundary constraint.",
    color: "#525252",
    opacity: 0.9,
    enabledByDefault: false,
    legendLabel: "Railway boundary",
    tpvdLayerName: "ctp:railway_boundary",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "railway-line",
    name: "railway-line",
    displayName: "Railway Line",
    category: "Constraint",
    geometryType: "line",
    description: "Rail line alignment.",
    color: "#171717",
    opacity: 0.9,
    enabledByDefault: false,
    legendLabel: "Railway line",
    tpvdLayerName: "ctp:railway_line",
    minZoom: 9,
    maxZoom: 19
  }),
  layer({
    id: "general-text",
    name: "general-text",
    displayName: "General Text",
    category: "Label",
    geometryType: "symbol",
    description: "General map text/annotation layer.",
    color: "#475569",
    opacity: 1,
    enabledByDefault: false,
    legendLabel: "General text",
    tpvdLayerName: "ctp:general_text",
    minZoom: 12,
    maxZoom: 19
  }),
  layer({
    id: "extra-layer",
    name: "extra-layer",
    displayName: "Extra TPS Layers",
    category: "Base",
    geometryType: "line",
    description: "TPVD extra layer group for special scheme overlays.",
    color: "#9333ea",
    opacity: 0.65,
    enabledByDefault: false,
    legendLabel: "Extra TPS layers",
    tpvdLayerName: "ctp:extra_layer",
    minZoom: 8,
    maxZoom: 19
  })
];

export const legendItems: LegendItem[] = gisLayers.map((layer) => ({
  layerId: layer.id,
  label: layer.legendLabel,
  color: layer.color,
  geometryType: layer.geometryType
}));
