import type { Plot } from "@/lib/schemas";

export const plotRecords: Plot[] = [
  {
    id: "plot-ahm-42-fp-118",
    plotId: "AHD-042-FP-118",
    tpsId: "tps-ahm-042",
    tpsName: "Science City Fringe TPS",
    tpsNumber: "42",
    district: "Ahmedabad",
    city: "Ahmedabad",
    urbanAuthority: "AUDA",
    village: "Sola",
    surveyNumber: "312/2",
    originalPlotNumber: "OP-64",
    finalPlotNumber: "FP-118",
    areaSqM: 1840,
    boundaryType: "Final Plot Boundary",
    roadAccess: "Primary frontage on 18 m TP road",
    nearbyRoadWidthM: 18,
    roadName: "Science City Approach Road",
    landUse: "Residential",
    zone: "R2",
    reservationType: null,
    fsi: 1.8,
    permissibleBuiltUpAreaSqM: 3312,
    setbacks: { frontM: 6, sideM: 3, rearM: 4.5 },
    heightLimitM: 45,
    restrictions: ["Verify final sanctioned measurements before design submission."],
    restrictionStatus: "Clear",
    intersections: {
      waterBody: false,
      gamthal: false,
      dpReservation: false,
      railway: false,
      htLine: false,
      roadBoundary: true
    },
    coordinates: [72.5035, 23.0752],
    relatedLayers: ["Final Plot Boundary", "Road Boundary", "Survey Number", "TPS Boundary"],
    sourceMetadata: "Mock TPVD-style plot record; replace with live cadastral/GIS feature service.",
    lastUpdated: "2026-04-18"
  },
  {
    id: "plot-ahm-42-fp-091",
    plotId: "AHD-042-FP-091",
    tpsId: "tps-ahm-042",
    tpsName: "Science City Fringe TPS",
    tpsNumber: "42",
    district: "Ahmedabad",
    city: "Ahmedabad",
    urbanAuthority: "AUDA",
    village: "Sola",
    surveyNumber: "309/1",
    originalPlotNumber: "OP-52",
    finalPlotNumber: "FP-091",
    areaSqM: 910,
    boundaryType: "Final Plot Boundary",
    roadAccess: "Secondary frontage on 9 m internal road",
    nearbyRoadWidthM: 9,
    roadName: "Sola TP Internal Road",
    landUse: "Residential",
    zone: "R1",
    reservationType: "Neighbourhood open space",
    fsi: 1.2,
    permissibleBuiltUpAreaSqM: 1092,
    setbacks: { frontM: 4.5, sideM: 2, rearM: 3 },
    heightLimitM: 24,
    restrictions: ["Part reservation edge requires authority confirmation.", "Internal road width may limit building height."],
    restrictionStatus: "Watch",
    intersections: {
      waterBody: false,
      gamthal: false,
      dpReservation: true,
      railway: false,
      htLine: false,
      roadBoundary: true
    },
    coordinates: [72.4998, 23.0737],
    relatedLayers: ["Final Plot Boundary", "DP Reservation", "Road Boundary", "Survey Line"],
    sourceMetadata: "Mock TPVD-style plot record; replace with live cadastral/GIS feature service.",
    lastUpdated: "2026-04-18"
  },
  {
    id: "plot-sur-18-fp-204",
    plotId: "SUR-018-FP-204",
    tpsId: "tps-sur-018",
    tpsName: "Vesu Urban Extension TPS",
    tpsNumber: "18",
    district: "Surat",
    city: "Surat",
    urbanAuthority: "SUDA",
    village: "Vesu",
    surveyNumber: "88/4",
    originalPlotNumber: "OP-87",
    finalPlotNumber: "FP-204",
    areaSqM: 2460,
    boundaryType: "Final Plot Boundary",
    roadAccess: "Corner plot with 24 m arterial and 12 m local road",
    nearbyRoadWidthM: 24,
    roadName: "Vesu Canal Road",
    landUse: "Mixed Use",
    zone: "MU",
    reservationType: "Canal influence buffer",
    fsi: 2.2,
    permissibleBuiltUpAreaSqM: 5412,
    setbacks: { frontM: 7.5, sideM: 4.5, rearM: 4.5 },
    heightLimitM: 55,
    restrictions: ["Canal/water body buffer to be verified from sanctioned plan."],
    restrictionStatus: "Watch",
    intersections: {
      waterBody: true,
      gamthal: false,
      dpReservation: false,
      railway: false,
      htLine: false,
      roadBoundary: true
    },
    coordinates: [72.7964, 21.1425],
    relatedLayers: ["Final Plot Boundary", "Water Body", "Road", "TPS Boundary"],
    sourceMetadata: "Mock TPVD-style plot record; replace with live cadastral/GIS feature service.",
    lastUpdated: "2026-03-29"
  },
  {
    id: "plot-vad-11-fp-037",
    plotId: "VAD-011-FP-037",
    tpsId: "tps-vad-011",
    tpsName: "Gotri Mixed Use TPS",
    tpsNumber: "11",
    district: "Vadodara",
    city: "Vadodara",
    urbanAuthority: "VUDA",
    village: "Gotri",
    surveyNumber: "142/1",
    originalPlotNumber: "OP-21",
    finalPlotNumber: "FP-037",
    areaSqM: 1325,
    boundaryType: "Original Plot Boundary",
    roadAccess: "12 m road access with compound wall edge",
    nearbyRoadWidthM: 12,
    roadName: "Gotri TP Road",
    landUse: "Commercial",
    zone: "C1",
    reservationType: "DP road widening",
    fsi: 1.6,
    permissibleBuiltUpAreaSqM: 2120,
    setbacks: { frontM: 6, sideM: 3, rearM: 3 },
    heightLimitM: 36,
    restrictions: ["DP road widening impact reduces effective frontage.", "Compound wall line must be reconciled on site."],
    restrictionStatus: "Restricted",
    intersections: {
      waterBody: false,
      gamthal: false,
      dpReservation: true,
      railway: false,
      htLine: true,
      roadBoundary: true
    },
    coordinates: [73.1454, 22.3231],
    relatedLayers: ["Original Plot Boundary", "HT Line", "Compound Wall", "DP Reservation"],
    sourceMetadata: "Mock TPVD-style plot record; replace with live cadastral/GIS feature service.",
    lastUpdated: "2026-02-11"
  },
  {
    id: "plot-raj-27-fp-066",
    plotId: "RAJ-027-FP-066",
    tpsId: "tps-raj-027",
    tpsName: "Mavdi Road TPS",
    tpsNumber: "27",
    district: "Rajkot",
    city: "Rajkot",
    urbanAuthority: "RUDA",
    village: "Mavdi",
    surveyNumber: "219/3",
    originalPlotNumber: "OP-73",
    finalPlotNumber: "FP-066",
    areaSqM: 720,
    boundaryType: "Final Plot Boundary",
    roadAccess: "Approach from 7.5 m local road",
    nearbyRoadWidthM: 7.5,
    roadName: "Mavdi Local Road",
    landUse: "Residential",
    zone: "R1",
    reservationType: "Gamtal interface",
    fsi: 1.0,
    permissibleBuiltUpAreaSqM: 720,
    setbacks: { frontM: 3, sideM: 1.5, rearM: 2 },
    heightLimitM: 15,
    restrictions: ["Gamtal boundary edge requires demarcation.", "Narrow access may limit redevelopment intensity."],
    restrictionStatus: "Watch",
    intersections: {
      waterBody: false,
      gamthal: true,
      dpReservation: false,
      railway: true,
      htLine: false,
      roadBoundary: true
    },
    coordinates: [70.7879, 22.2627],
    relatedLayers: ["Final Plot Boundary", "Gamtal Boundary", "Railway Boundary", "Road"],
    sourceMetadata: "Mock TPVD-style plot record; replace with live cadastral/GIS feature service.",
    lastUpdated: "2026-01-24"
  }
];
